# Generated by Django 5.0.4 on 2024-08-01 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='phone',
            field=models.IntegerField(blank=True),
        ),
    ]
