
# Generated by Django 5.0.4 on 2024-07-29 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='model_car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_car', to='vehiculos.modelo'),
        ),
    ]
