# Generated by Django 5.0.4 on 2024-07-29 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0003_alter_car_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(null=True, upload_to='vehiculos_images/'),
        ),
    ]
