# Generated by Django 5.0.4 on 2024-08-05 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0005_alter_car_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('observations', models.CharField(default='.', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Gama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Transmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='km',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='fuel',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AddField(
            model_name='car',
            name='bodyWork',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bodyWork', to='vehiculos.bodywork'),
        ),
        migrations.AddField(
            model_name='car',
            name='condition',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='condition', to='vehiculos.condition'),
        ),
        migrations.AddField(
            model_name='car',
            name='gama',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='gama', to='vehiculos.gama'),
        ),
        migrations.AddField(
            model_name='car',
            name='transmission',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transmission', to='vehiculos.transmission'),
        ),
        migrations.CreateModel(
            name='VehiculoReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('rating', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='vehiculos.car')),
            ],
        ),
    ]
