# Generated by Django 5.0.4 on 2024-08-05 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0006_bodywork_condition_gama_transmission_car_km_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='bodyWork',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bodyWork', to='vehiculos.bodywork'),
        ),
        migrations.AlterField(
            model_name='car',
            name='condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condition', to='vehiculos.condition'),
        ),
        migrations.AlterField(
            model_name='car',
            name='gama',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gama', to='vehiculos.gama'),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transmission', to='vehiculos.transmission'),
        ),
    ]
