# Generated by Django 5.0.4 on 2024-08-05 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0007_alter_car_bodywork_alter_car_condition_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='condition',
            name='observations',
        ),
    ]
